services:
  mrp-db:
    image: postgres:15
    container_name: mrp-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mrp_db
    ports:
      - "5432:5432"
    volumes:
      - mrp-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5

  mrp-backend:
    build: .
    container_name: mrp-backend
    restart: always
    depends_on:
      mrp-db:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      DB_HOST: mrp-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mrp_db
      DATABASE_URL: "postgres://user:password@mrp-db:5432/mrp_db"
      NODE_ENV: development
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mrp-db-data:
