services:
  db:
    image: postgres:15
    container_name: mrp-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mrp_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: mrp-backend
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 4000
      PG_URI: postgresql://admin:secret@db:5432/mrp_backend
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npx", "nodemon", "src/server.js"]

volumes:
  postgres_data: